import type { Insight } from "@/types/analysis";

interface InsightsPanelProps {
  insights: Insight[];
}

export function InsightsPanel({ insights }: InsightsPanelProps) {
  if (insights.length === 0) {
    return (
      <div className="card p-5 text-sm text-foreground-muted">
        No tactical insights were generated for this analysis.
      </div>
    );
  }

  return (
    <div className="card flex flex-col gap-3 p-5">
      <div className="flex items-center justify-between">
        <h3 className="text-sm font-semibold">Tactical insights</h3>
        <span className="text-xs text-foreground-muted">AI interpretation, layered on CV facts</span>
      </div>
      <ul className="flex flex-col gap-2.5">
        {insights.map((insight, i) => (
          <li key={i} className="flex items-start gap-2.5 text-sm">
            <span className="mt-0.5 text-accent">▸</span>
            <span className="flex-1">{insight.text}</span>
            <span
              className={`shrink-0 rounded-full px-2 py-0.5 text-[10px] font-medium uppercase tracking-wide ${
                insight.source === "ai_interpretation"
                  ? "bg-accent/15 text-accent"
                  : "bg-surface-muted text-foreground-muted"
              }`}
              title={
                insight.source === "ai_interpretation"
                  ? "Generated by an LLM from structured CV stats only"
                  : "Deterministic rule-based commentary (no AI key configured)"
              }
            >
              {insight.source === "ai_interpretation" ? "AI" : "rule-based"}
            </span>
          </li>
        ))}
      </ul>
    </div>
  );
}
