import type { Insight } from "@/types/analysis";
import { SparkIcon } from "@/components/icons";

interface InsightsPanelProps {
  insights: Insight[];
}

export function InsightsPanel({ insights }: InsightsPanelProps) {
  return (
    <section className="card flex flex-col p-5">
      <div className="flex items-center justify-between gap-3">
        <h3 className="eyebrow">Tactical insights</h3>
        <span className="text-[11px] text-ink-3">Interpretation, layered on CV facts</span>
      </div>

      {insights.length === 0 ? (
        <p className="mt-3 border-t border-line-soft pt-4 text-[14px] text-ink-3">
          No tactical insights were generated for this analysis.
        </p>
      ) : (
        <ul className="mt-3 flex flex-col divide-y divide-line-soft border-t border-line-soft">
          {insights.map((insight, i) => {
            const isAi = insight.source === "ai_interpretation";
            return (
              <li key={i} className="flex items-start gap-3 py-3">
                <span
                  className={`mt-0.5 flex h-6 w-6 shrink-0 items-center justify-center rounded-md ${
                    isAi ? "bg-grass-100 text-grass-700" : "bg-surface-sunk text-ink-3"
                  }`}
                >
                  <SparkIcon size={14} />
                </span>
                <p className="flex-1 text-[14px] leading-relaxed">{insight.text}</p>
                <span
                  className={`mt-0.5 shrink-0 rounded-sm px-1.5 py-0.5 text-[10px] font-semibold uppercase tracking-[0.05em] ${
                    isAi ? "bg-grass-100 text-grass-700" : "bg-surface-sunk text-ink-3"
                  }`}
                  title={
                    isAi
                      ? "Generated by an LLM from structured CV stats only"
                      : "Deterministic rule-based commentary (no AI key configured)"
                  }
                >
                  {isAi ? "AI" : "Rule"}
                </span>
              </li>
            );
          })}
        </ul>
      )}
    </section>
  );
}
